In [9]:
import numpy as np
import cv2
import glob
import ntpath
import os
from PIL import Image

In [10]:
def flatten(seq):
  for el in seq:
    if isinstance(el, list):
      yield from flatten(el)
    else:
      yield el

In [11]:
filelist=glob.glob('./thermal2/*.txt')

In [12]:
for i in filelist:
    print(i)
    values=[]
    with open(i) as f:
        for line in f:
            linelist=line.split(" ")
            lineint=[int(i) for i in linelist]
            values.append(lineint)
        
    print(np.mean(values))
    white=max(flatten(values))
    black=min(flatten(values))
    if black!=white:
        for index,line in enumerate(values):
            for ind,v in enumerate(line):
                values[index][ind]=int((v-black)/(white-black)*255)
        im = np.array(values, dtype = np.uint8)
        print(im)

        vmin=30300
        vmax=31300
        vmint=int((vmin-black)/(white-black)*255)
        vmaxt=int((vmax-black)/(white-black)*255)

        thresh=29800
        thresht=int((thresh-black)/(white-black)*255)
        #res2 = cv2.inRange(im, 200, 255)
        res3 = cv2.inRange(im, 150, 255)
        #res4 = cv2.inRange(im, 100, 255)
        

        #im_v = cv2.hconcat([im,res2,res3,res4])
        #cv2.imshow('image',im_v)
        #cv2.imshow('image',res3)
        cv2.waitKey(0)
        cv2.destroyAllWindows()
        filename=ntpath.basename(i)
        pre=filename.split(".")[0]
        fi='./threshold-thermal2/'+pre+".png"
        cv2.imwrite(fi,res3)
        img = cv2.imread('./threshold-thermal2/'+pre+".png",0)

            


./thermal2\1560251223589-temperatures.txt
30098.810364583333
[[85 86 86 ... 92 92 92]
 [86 86 86 ... 92 92 92]
 [86 87 87 ... 92 92 92]
 ...
 [84 84 84 ... 91 92 92]
 [84 84 84 ... 91 92 92]
 [84 85 85 ... 91 91 92]]
./thermal2\1562084490444-temperatures.txt
29802.40947916667
[[23 23 24 ... 29 29 29]
 [23 23 24 ... 29 29 29]
 [23 24 24 ... 29 29 29]
 ...
 [28 28 28 ... 16 16 16]
 [28 28 28 ... 16 16 16]
 [28 28 28 ... 16 16 17]]
./thermal2\1566904246700-temperatures.txt
21313.0
./thermal2\1566904247734-temperatures.txt
29884.850546875
[[96 97 97 ... 89 89 89]
 [96 96 97 ... 89 89 89]
 [96 96 96 ... 89 89 89]
 ...
 [66 66 66 ... 39 39 38]
 [66 66 66 ... 40 40 39]
 [66 66 66 ... 41 41 40]]
./thermal2\1566904248818-temperatures.txt
29811.02162760417
[[79 79 79 ... 80 80 80]
 [79 79 79 ... 80 80 80]
 [79 79 79 ... 80 80 80]
 ...
 [59 59 59 ... 37 36 36]
 [58 58 58 ... 38 37 37]
 [58 58 58 ... 40 40 40]]
./thermal2\1566904249897-temperatures.txt
29783.718294270835
[[82 82 82 ... 80 80 80]
 

[[20 20 20 ... 20 20 20]
 [20 20 20 ... 20 20 20]
 [20 20 20 ... 20 20 19]
 ...
 [ 8  8  8 ...  3  3  3]
 [ 8  8  8 ...  3  3  3]
 [ 8  8  8 ...  3  3  3]]
./thermal2\1566904287858-temperatures.txt
29678.31171875
[[21 21 21 ... 19 19 19]
 [21 21 21 ... 19 19 18]
 [20 20 21 ... 19 18 18]
 ...
 [ 7  7  7 ...  2  3  3]
 [ 7  7  7 ...  2  2  3]
 [ 7  7  7 ...  2  2  3]]
./thermal2\1566904288903-temperatures.txt
30450.492421875
[[250 250 250 ... 253 253 253]
 [250 250 250 ... 253 253 253]
 [250 250 250 ... 253 253 253]
 ...
 [  9   8   8 ... 188 191 194]
 [  9   8   8 ... 185 189 192]
 [  8   8   8 ... 182 185 189]]
./thermal2\1566904289936-temperatures.txt
29890.765520833334
[[  7   7   7 ...   3   3   3]
 [  7   7   7 ...   3   3   3]
 [  7   7   7 ...   3   3   3]
 ...
 [  6   6   5 ... 222 223 224]
 [  6   6   5 ... 221 221 222]
 [  6   6   5 ... 219 220 221]]
./thermal2\1566904331042-temperatures.txt
29890.765520833334
[[  7   7   7 ...   3   3   3]
 [  7   7   7 ...   3   3   3]
 [  7

[[29 29 29 ... 29 30 30]
 [28 28 28 ... 30 30 30]
 [28 27 27 ... 30 30 30]
 ...
 [36 36 37 ... 26 26 26]
 [37 37 37 ... 26 26 26]
 [37 37 37 ... 26 26 26]]
./thermal2\1566904369549-temperatures.txt
29669.8819921875
[[24 24 23 ... 25 25 25]
 [23 24 23 ... 24 24 25]
 [23 24 23 ... 24 24 25]
 ...
 [34 34 34 ... 23 24 24]
 [34 34 34 ... 23 24 24]
 [34 34 34 ... 23 24 24]]
./thermal2\1566904370603-temperatures.txt
29668.0376953125
[[24 24 24 ... 24 24 24]
 [24 24 24 ... 24 24 24]
 [24 24 24 ... 24 24 24]
 ...
 [37 37 37 ... 26 26 26]
 [37 37 37 ... 26 26 26]
 [37 37 37 ... 26 26 26]]
./thermal2\1566904371673-temperatures.txt
29674.006966145833
[[25 24 24 ... 27 28 28]
 [25 24 24 ... 27 27 27]
 [25 24 24 ... 27 27 27]
 ...
 [36 36 36 ... 26 26 26]
 [36 36 36 ... 26 26 26]
 [36 36 36 ... 26 26 26]]
./thermal2\1566904372724-temperatures.txt
29725.014466145833
[[17 17 17 ... 17 17 17]
 [17 17 16 ... 17 17 17]
 [17 17 16 ... 17 17 17]
 ...
 [31 31 31 ... 16 16 16]
 [31 31 31 ... 16 16 16]
 [31 3

[[93 93 94 ... 91 93 94]
 [93 93 93 ... 93 94 95]
 [93 93 93 ... 93 94 95]
 ...
 [96 95 95 ... 64 64 64]
 [96 95 95 ... 64 64 64]
 [96 96 96 ... 64 64 64]]
./thermal2\1566904409445-temperatures.txt
29769.050416666665
[[95 95 94 ... 91 92 93]
 [94 94 94 ... 90 92 93]
 [94 94 94 ... 90 92 93]
 ...
 [98 98 98 ... 63 63 63]
 [98 98 98 ... 63 63 63]
 [98 98 98 ... 64 64 64]]
./thermal2\1566904410481-temperatures.txt
29785.441783854167
[[ 96  96  95 ...  92  93  94]
 [ 96  96  95 ...  92  93  94]
 [ 96  96  94 ...  91  92  94]
 ...
 [100 100  97 ...  69  69  69]
 [100 100  99 ...  69  69  69]
 [100 100 100 ...  69  69  69]]
./thermal2\1566904411551-temperatures.txt
29793.254466145834
[[102 102 102 ...  96  96  98]
 [102 101 101 ...  95  96  96]
 [102 101 100 ...  94  96  96]
 ...
 [102 102 101 ...  66  66  66]
 [102 102 102 ...  66  66  66]
 [103 102 102 ...  68  68  68]]
./thermal2\1566904412564-temperatures.txt
29811.00420572917
[[96 96 96 ... 87 88 89]
 [96 96 96 ... 87 87 88]
 [96 96 96 

In [17]:
import glob
import cv2
import numpy as np
filelist=glob.glob('./threshold-thermal2/*.png')
image_number = 0
for i in filelist:
    image = cv2.imread(i)
    original = image.copy()
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    blurred = cv2.GaussianBlur(gray, (3, 3), 0)
    canny = cv2.Canny(blurred, 120, 255, 1)
    kernel = np.ones((5,5),np.uint8)
    dilate = cv2.dilate(canny, kernel, iterations=1)

    # Find contours
    cnts = cv2.findContours(dilate, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    cnts = cnts[0] if len(cnts) == 2 else cnts[1]

    # Iterate thorugh contours and filter for ROI
   
    for c in cnts:
        x,y,w,h = cv2.boundingRect(c)
        cv2.rectangle(image, (x, y), (x + w, y + h), (36,255,12), 2)
        ROI = original[y:y+h, x:x+w]
        cv2.imwrite("{} ROI.png".format(image_number), ROI)
        image_number += 1
        area = cv2.contourArea(c)
        #print(area)
    
    #cv2.imshow('canny', canny)
    #cv2.imshow('image', image)
    #cv2.waitKey(0)

In [3]:
# Imports
import random, cv2, os, sys, shutil
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
import numpy as np
import keras
import csv
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches



Using TensorFlow backend.


In [4]:
class image_clustering:

    def __init__(self, folder_path="data", n_clusters=3, max_examples=500, use_imagenets=False, use_pca=False):
        paths = os.listdir(folder_path)
        if max_examples == None:
            self.max_examples = len(paths)
        else:
            if max_examples > len(paths):
                self.max_examples = len(paths)
            else:
                self.max_examples = max_examples
        self.n_clusters = n_clusters
        self.folder_path = folder_path
        random.shuffle(paths)
        self.image_paths = paths[:self.max_examples]
        self.use_imagenets = use_imagenets
        self.use_pca = use_pca
        del paths 
        try:
            shutil.rmtree("output")
        except FileExistsError:
            pass
        print("\n output folders created.")
        os.makedirs("output")
        for i in range(self.n_clusters):
            os.makedirs("output\\cluster" + str(i))
        print("\n Object of class \"image_clustering\" has been initialized.")

    def load_images(self):
        self.images = []
        for image in self.image_paths:
            self.images.append(cv2.cvtColor(cv2.resize(cv2.imread(self.folder_path + "\\" + image), (224,224)), cv2.COLOR_BGR2RGB))
        self.images = np.float32(self.images).reshape(len(self.images),-1)
        self.images /= 255
        print("\n " + str(self.max_examples) + " images from the \"" + self.folder_path + "\" folder have been loaded in a random order.")

    def get_new_imagevectors(self):
        if self.use_imagenets == False:
            self.images_new = self.images
        else:
            if use_imagenets.lower() == "vgg16":
                model1 = keras.applications.vgg19.vgg19(include_top=False, weights="imagenet", input_shape=(224,224,3))
            elif use_imagenets.lower() == "vgg19":
                model1 = keras.applications.vgg19.vgg19(include_top=False, weights="imagenet", input_shape=(224,224,3))
            elif use_imagenets.lower() == "resnet50":
                model1 = keras.applications.resnet50.ResNet50(include_top=False, weights="imagenet", input_shape=(224,224,3))
            elif use_imagenets.lower() == "xception":
                model1 = keras.applications.xception.Xception(include_top=False, weights='imagenet',input_shape=(224,224,3))
            elif use_imagenets.lower() == "inceptionv3":
                model1 = keras.applications.inception_v3.InceptionV3(include_top=False, weights='imagenet', input_shape=(224,224,3))
            elif use_imagenets.lower() == "inceptionresnetv2":
                model1 = keras.applications.inception_resnet_v2.InceptionResNetV2(include_top=False, weights='imagenet', input_shape=(224,224,3))
            elif use_imagenets.lower() == "densenet":
                model1 = keras.applications.densenet.DenseNet201(include_top=False, weights='imagenet', input_shape=(224,224,3))
            elif use_imagenets.lower() == "mobilenetv2":
                model1 = keras.applications.mobilenetv2.MobileNetV2(input_shape=(224,224,3), alpha=1.0, depth_multiplier=1, include_top=False, weights='imagenet', pooling=None)
            else:
                print("\n\n Please use one of the following keras applications only [ \"vgg16\", \"vgg19\", \"resnet50\", \"xception\", \"inceptionv3\", \"inceptionresnetv2\", \"densenet\", \"mobilenetv2\" ] or False")
                sys.exit()

            pred = model1.predict(self.images)
            images_temp = pred.reshape(self.images.shape[0], -1)
            if self.use_pca == False: 
                self.images_new = images_temp
            else: 
                model2 = PCA(n_components=None, random_state=728)
                model2.fit(images_temp)
                self.images_new = model2

    def clustering(self):
        estimator = KMeans(n_clusters=self.n_clusters, n_jobs=-1, random_state=728)
        estimator.fit(self.images_new)
        predictions = estimator.predict(self.images_new)
        np.savetxt("predictions.csv", predictions, delimiter=",", fmt='%s', header=header)
        predictions1= estimator.transform(self.images_new)
        np.savetxt("predictions1.csv", predictions1, delimiter=",", fmt='%s', header=header)
        #predicarray = np.array(predictions1)
        #print(model.inertia_)
        cluster0=[]
        cluster1=[]
        cluster2=[]
        cluster3=[]
        p0=[]
        p1=[]
        p2=[]
        p3=[]
        #for i in predictions:
        #    if predictions[i]==0:
        #        #print (predictions[i])
        #        p0.append(predictions1[])
        #        cluster0.append(p0[0][i])
        #        #print(predictions1[:, 0])
        #for i in predictions:
        #    if predictions[i]==1:
        #        #print (predictions[i])
        #        p1.append(predictions1[0][i])
        #        cluster1.append(p1[0][i])
        #        #print(predictions1[:, 0])
        #for i in predictions:
        #    if predictions[i]==2:
        #        #print (predictions[i])
        #        p2.append(predictions1[0][i])
        #        cluster2.append(p2[0][i])
        #        #print(predictions1[:, 0])
        #for i in predictions:
        #    if predictions[i]==3:
        #        #print (predictions[i])
        #        p3.append(predictions1[0][i])
        #        cluster3.append(p3[0][i])
        #        #print(predictions1[:, 0])
        #print(cluster0)
        #print(cluster1)
        #print(cluster2)
        #print(cluster3)
        #print(predictions)
        for i in range(self.max_examples):
            shutil.copy2(self.folder_path+"\\"+self.image_paths[i], "output\cluster"+str(predictions[i]))
        print("\n Clustering complete! \n\n Clusters and the respective images are stored in the \"output\" folder.")
        #empty dictionaries

        print("shape of prediction: " + str(predictions1.shape))
        clusters_centroids=dict()
        clusters_radii= dict()
        for cluster in range(0,self.n_clusters):

            clusters_centroids[cluster]=list(zip(estimator.cluster_centers_[:, 0],estimator.cluster_centers_[:,1]))[cluster]
            clusters_radii[cluster] = max([np.linalg.norm(np.subtract(i,clusters_centroids[cluster])) for i in zip(self.images_new[predictions == cluster, 0],self.images_new[predictions == cluster, 1])])
        
        #Visualising the clusters and cluster circles

        fig, ax = plt.subplots(1,figsize=(7,5))

        plt.scatter(self.images_new[predictions == 0, 0], self.images_new[predictions == 0, 0], s = 100, c = 'red', label = 'Cluster 1')
        art = mpatches.Circle(clusters_centroids[0],clusters_radii[0], edgecolor='r',fill=False)
        ax.add_patch(art)

        plt.scatter(self.images_new[predictions == 1, 0], self.images_new[predictions == 1, 0], s = 100, c = 'blue', label = 'Cluster 2')
        art = mpatches.Circle(clusters_centroids[1],clusters_radii[1], edgecolor='b',fill=False)
        ax.add_patch(art)

        plt.scatter(self.images_new[predictions == 2, 0], self.images_new[predictions == 2, 1], s = 100, c = 'green', label = 'Cluster 3')
        art = mpatches.Circle(clusters_centroids[2],clusters_radii[2], edgecolor='g',fill=False)
        ax.add_patch(art)

        #Plotting the centroids of the clusters
        plt.scatter(estimator.cluster_centers_[:, 0], estimator.cluster_centers_[:,1], s = 100, c = 'yellow', label = 'Centroids')

        plt.legend()
        plt.tight_layout()
        plt.savefig('kmeans.jpg',dpi=300)
        print(clusters_centroids)
        print(clusters_radii)

In [5]:
if __name__ == "__main__":

	print("\n\n \t\t START\n\n")

	number_of_clusters = 4 # cluster names will be 0 to number_of_clusters-1

	data_path = "C:/Users/dar/Desktop/Unsupervised-Object-Clustering-master/ROI" # path of the folder that contains the images to be considered for the clustering (The folder must contain only image files)

	max_examples = 500 # number of examples to use, if "None" all of the images will be taken into consideration for the clustering
	# If the value is greater than the number of images present  in the "data_path" folder, it will use all the images and change the value of this variable to the number of images available in the "data_path" folder. 

	use_imagenets = False
	# choose from: "Xception", "VGG16", "VGG19", "ResNet50", "InceptionV3", "InceptionResNetV2", "DenseNet", "MobileNetV2" and "False" -> Default is: False
	# you have to use the correct spelling! (case of the letters are irrelevant as the lower() function has been used)

	if use_imagenets == False:
		use_pca = False
	else:
		use_pca = False # Make it True if you want to use PCA for dimentionaity reduction -> Default is: False

	temp = image_clustering(data_path, number_of_clusters, max_examples, use_imagenets, use_pca)
	temp.load_images()
	temp.get_new_imagevectors()
	temp.clustering()

	print("\n\n\t\t END\n\n")



 		 START



 output folders created.

 Object of class "image_clustering" has been initialized.

 183 images from the "C:/Users/dar/Desktop/Unsupervised-Object-Clustering-master/ROI" folder have been loaded in a random order.


NameError: name 'header' is not defined

In [83]:
filelist=glob.glob('C:/Users/dar/Desktop/Segmentation/output/cluster3/*.png')
areas=[]
for i in filelist:
    #image = cv2.imread(i)
    image = cv2.imread(i)
    original = image.copy()
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    blurred = cv2.GaussianBlur(gray, (3, 3), 0)
    canny = cv2.Canny(blurred, 120, 255, 1)
    kernel = np.ones((5,5),np.uint8)
    dilate = cv2.dilate(canny, kernel, iterations=1)
    cnts = cv2.findContours(dilate, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    cnts = cnts[0] if len(cnts) == 2 else cnts[1]
    for c in cnts:
        area = cv2.contourArea(c)
        #print(area)
        areas.append(area)
print(areas)
#with open('imagearea.csv', mode='a') as csv_file:
    #fieldnames = ['Image Name', 'Area']
    #writer = csv.DictWriter(csv_file, fieldnames=fieldnames)

    #writer.writeheader()
    #writer.writerow({'Image Name': i, 'Area': areas})

NameError: name 'glob' is not defined

ModuleNotFoundError: No module named 'core'



 		 START



 output folders created.

 Object of class "image_clustering" has been initialized.

 183 images from the "C:/Users/dar/Desktop/Segmentation/ROI" folder have been loaded in a random order.


ValueError: Error when checking input: expected input_1 to have 4 dimensions, but got array with shape (183, 150528)

ModuleNotFoundError: No module named 'neupy'

In [ ]:
for c in cnts:
        (x,y),radius = cv2.minEnclosingCircle(c)
        center = (int(x),int(y))
        radius = int(radius)
        img = cv2.circle(image,center,radius,(0,255,0),2)
        ROI = original[y:y, x:x]
        print('Contour: centre {},{}, radius {}'.format(x,y,radius))
